### ISSUE TITLE
Supports .md files?

### ISSUE THREAD

**Issue by yoongfook** [hashicorp/next-mdx-enhanced#19]
The `next-mdx` plugin allows for matching `.md` files for compilation, but seems like its not supported here?

https://github.com/hashicorp/next-mdx-enhanced/blob/4413846d4d43665ae906b56f276f7e8b5db0ce5e/babelPlugin.js#L13-L15

Will it be an easy one to add? 😊

**Comment by jescalan** [comment]
Yeah I'd welcome a pull request to make it configurable! Perhaps an option like `matchExtensions` - this would be a great first contribution. 

My only request is that I'd like to keep only `.mdx` as the default, since the files are parsed using `mdx` and not a standard markdown parser. I feel like its best to keep things clear by default.
