### ISSUE TITLE
Possible to use MDXProvider / components customization?

### ISSUE THREAD

**Issue by samselikoff** [hashicorp/next-mdx-enhanced#76]
Hi there! Thanks for putting this great lib together ✨

I'm moving my personal site from Gatsby to Next and trying to bring along my MDX setup.

Over there it looks something like this:

```
<MDXProvider components={components}>
  <div className="mb-8 md:mb-10">
    <h1 className="mt-8 text-3xl font-semibold leading-tight md:text-4xl lg:text-4-5xl">
      {props.data.mdx.frontmatter.title}
    </h1>
  </div>
  <MDXRenderer>{mdx.body}</MDXRenderer>
</MDXProvider>
```

where `components` is an object mapping tags like `h2` to React components, like this:

```js
const components = {
  h2: ({ children, ...rest }) => (
    <h2
      className="mt-12 text-lg font-semibold leading-tight text-gray-900 md:text-2xl"
      {...rest}
    >
      {children}
    </h2>
  ),
}
```

I was wondering if it this functionality was possible using `next-mdx-enhanced`? I don't have webpack experience so how this is all getting wired up is a bit of a black box to me.

If not, what's the recommended way to customize the styling for MDX content?

Thank you!

**Comment by jescalan** [comment]
Yes, it is possible. This doesn't involve webpack at all and works exactly the same way - just use an `MDXProvider` and pass it the components you want to be available.

You might also benefit slightly more from using [`next-mdx-remote`](https://github.com/hashicorp/next-mdx-remote) which has a more natural data loading pattern, better performance, and gives you a very direct interface to the components that you want to make available rather than requiring an extra provider.

Closing as this is a question and not an issue, but please feel free to continue following up!

**Comment by samselikoff** [comment]
Thank you for the quick response!

Ah I see – the `content` that comes in through the layout can be wrapped in a Provider just like in my gatsby site. Perfect, seems to be working great!

And thanks for mentioning `next-mdx-remote`, looks like the spiritual successor to this project. Would you say there is no real reason to use `next-mdx-enhanced` on new projects, and we should just prefer `next-mdx-remote`?

**Comment by jescalan** [comment]
Pretty much, yes. `next-mdx-remote` is newer so I haven't yet posted a notice saying that this project is deprecated, but that is likely what is going to happen as it matures 😀

**Comment by samselikoff** [comment]
Awesome- thanks again for the quick info + all your work!
